[fix] getting rid of error TS2339
Property 'assign' does not exist on type 'ObjectConstructor'. The code
works but I could not get rid of unless we use the “ponyfill”. This
package is probably being brought by some other package, perhaps a dev
dependency so we may have to come with another solution.